version: '3'

services:
  postgres:
    image: postgres
    container_name: storage_pg
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=storage
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin